crowdsourcing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from .views import *


#admin.site.site_header = 'Peda Reporter'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crowdusers.urls')),
    path('api/v1/', include('mobile_api.urls')),
    path('admin-site/', include('crowdsourceadmin.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/activate/<str:username>/', Account.activate_user_account, name='activate_account'),
    path('accounts/reset-password/', Account.change_password, name="reset_password"),
    path('accounts/reset-password/send-email/', Account.send_password_reset_email, name="send_password_reset_email"),
    path('accounts/signup/', Account.as_view(), name='signup'),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
]

crowdusers/urls.py
from django.urls import path
from .views import *

app_name = 'crowdusers'
urlpatterns = [
    path('', index, name="index"),
    path('about-us/', about, name="about"),
    path('contact-us/', contact, name="contact"),
    path('create-deployment/', deployment, name="deployment"),
    path('create-deployment/persist-deployment/', persist_deployment, name="persist_deployment"),
    path('deployments/<int:dep_pk>/', get_single_deployment_details, name="single_deployment_details"),
    path('deployments/single-deployment-details/<int:dep_pk>/', single_deployment_details, name="single_deployment_details_template"),
    path('forward-to-response-body/', forward_report_to_response_body, name='forward_report_to_response_body'),
    #path('deployments/location/<str:lat>/<str:lng>/', get_location_from_latlng, name="get_location_from_latlng"),
    path('create-deployment/persist-deployment-images/<int:rand_deployment_number>/', persist_deployment_images, name="persist_deployment_images"),
]

crowdusers/models.py
from django.contrib.auth.models import User
from django.db import models


class ReportNature(models.Model):
    name = models.CharField(max_length=25, blank=False)

    def __str__(self):
        return self.name


class Deployment(models.Model):
    report_brief_description = models.CharField(max_length=200, blank=False)
    report_nature = models.CharField(max_length=15, blank=False)
    report_full_description = models.TextField(blank=False)
    reporter_background = models.CharField(max_length=25, blank=False)
    deployment_location = models.CharField(max_length=100, blank=True)
    latitude = models.CharField(max_length=20, blank=False)
    longitude = models.CharField(max_length=20, blank=False)
    report_date = models.CharField(max_length=12, blank=False)
    report_time = models.CharField(max_length=12, blank=False)
    report_time_frame = models.CharField(max_length=120, blank=False)
    report_response_bodies = models.CharField(max_length=255, blank=True)
    report_video_link = models.CharField(max_length=255, blank=True)
    report_views = models.IntegerField(blank=True, default=0)
    deployment_number = models.CharField(max_length=10, blank=True)
    report_platform = models.CharField(max_length=10, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.report_brief_description

    class Meta:
        ordering = ['-created_date']


class DeploymentImages(models.Model):
    deployment_number = models.CharField(max_length=10, blank=False)
    file = models.ImageField(upload_to='deployment/images/')
    uploaded_at = models.DateTimeField(auto_now_add=True)


class CustomUser(User):
    RESPONSE_BODY_NAMES = [
        ('mavissewornu05@gmail.com', 'Ghana Police'),
        ('mavissewornu05@gmail.com', 'NADMO'),
        ('mavissewornu05@gmail.com', 'Emergency Medical Technicians'),
    ]
    display_name = models.CharField(max_length=55, blank=True)
    is_response_body = models.BooleanField(default=False, blank=True)
    response_bodies = models.CharField(max_length=50, choices=RESPONSE_BODY_NAMES, blank=True)

    def __str__(self):
        return self.display_name

    class Meta:
        verbose_name = 'Response Body'

crowdusers/forms.py
from django.forms import ModelForm
from .models import *
from django import forms


class DeploymentForm(ModelForm):
    class Meta:
        model = Deployment
        exclude = ['created_date', 'user']


class DeploymentImagesForm(ModelForm):
    class Meta:
        model = DeploymentImages
        fields = ('file',)


class CustomUserForm(ModelForm):
    confirm_password = forms.CharField(label=("Password"),
                                widget=forms.PasswordInput(render_value=False))

    def __init__(self, *args, **kwargs):
        super(CustomUserForm, self).__init__(*args, **kwargs)
        self.fields['password'].widget.attrs['autocomplete'] = 'off'

        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
                'required': 'required',
            })

    class Meta:
        model = CustomUser
        fields = ['email', 'display_name', 'password']
        labels = {'display_name': 'Display Name'}


class ResponseBodyForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(ResponseBodyForm, self).__init__(*args, **kwargs)
        self.fields['password'].widget.attrs['autocomplete'] = 'off'

        for name in self.fields.keys():
            self.fields[name].widget.attrs.update({
                'class': 'form-control',
                'required': 'required',
            })

    class Meta:
        model = CustomUser
        fields = ['email', 'display_name', 'password']
        labels = {'display_name': 'Response Body Name'}


class ForwardToResponseBodyForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['display_name', 'email', 'response_bodies']
        widgets = {
            'response_bodies': forms.Select(choices=CustomUser.RESPONSE_BODY_NAMES,
                                             attrs={'class': 'form-control', 'required': 'required'}),
        }

crowdusers/views.py
import json
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.conf import settings
from crowdsourcing.serializers import DeploymentSerializer, ImageSerializer
from .forms import *
from django.contrib import messages
from .utils import CrowdSourcingUtils


def index(request):
    deployment_location_details = []
    deployment_details = {}
    form = ForwardToResponseBodyForm()
    for dep in Deployment.objects.all():
        deployment_details = {'location': dep.deployment_location, 'lat': dep.latitude,
                              'lng': dep.longitude}
        deployment_location_details.append(deployment_details)
    context = {
        'index': 'true',
        'deployments': CrowdSourcingUtils.paginate_deployments(request, Deployment.objects.all()),
        'deployment_location_details': json.dumps(deployment_location_details),
        'form': form
    }
    return render(request, 'crowdusers/index.html', context)


def get_single_deployment_details(request, **kwargs):
    if request.is_ajax and request.method == "GET":
        dep_pk = kwargs.get('dep_pk', None)
        if dep_pk:
            try:
                single_deployment = Deployment.objects.get(pk=dep_pk)
                single_deployment_images = DeploymentImages.objects.filter(
                    deployment_number=single_deployment.deployment_number).first()
                days_since_deployment = CrowdSourcingUtils.days_since_deployment(single_deployment.report_date)
                serializer = DeploymentSerializer(instance=single_deployment)
                image_serializer = ImageSerializer(instance=single_deployment_images)

                # update views for this deployment when someone views for the first time
                if not 'viewed_deployment_%s' % dep_pk in request.session:
                    request.session['viewed_deployment_%s' % dep_pk] = True
                    single_deployment.report_views += 1
                    single_deployment.save()
                return JsonResponse({"data": serializer.data, "images": image_serializer.data,
                                     'days_since_deployment': days_since_deployment}, status=200)
            except Deployment.DoesNotExist:
                return JsonResponse({"status": '404', 'error': 'No deployment found with the id %s ' % dep_pk},
                                    status=400)
        else:
            return JsonResponse({"error": '403', 'message': 'Invalid id for deployment'})


def about(request):
    return render(request, 'crowdusers/about.html', {'about': 'true'})


def contact(request):
    return render(request, 'crowdusers/contact-us.html', {'contact': 'true'})


def single_deployment_details(request, **kwargs):
    dep_pk = kwargs.get('dep_pk', None)
    dep = Deployment.objects.get(pk=dep_pk)
    single_deployment_images = DeploymentImages.objects.filter(
        deployment_number=dep.deployment_number).first()
    days_since_deployment = CrowdSourcingUtils.days_since_deployment(dep.report_date)
    context = {
        'deployment': dep,
        'image': single_deployment_images,
        'days_since_deployment': days_since_deployment
    }
    return render(request, 'crowdusers/single-deployment-details.html', context)


@login_required
def deployment(request):
    report_nature = ReportNature.objects.all()
    context = {
        'report_nature': report_nature,
        'deployment': 'true'
    }
    return render(request, 'crowdusers/create-deployment.html', context)


def persist_deployment(request):
    if 'random_deployment_number' in request.session:
        random_deployment_number = request.session['random_deployment_number']
    form = DeploymentForm(request.POST, request.FILES)
    if form.is_valid():
        user_deployment = form.save(commit=False)
        user_deployment.deployment_number = random_deployment_number
        user_deployment.user = request.user
        user_deployment.report_platform = 'Web'
        user_deployment.deployment_location = CrowdSourcingUtils.get_location_from_latlng(form.cleaned_data['latitude'],
                                                                                          form.cleaned_data[
                                                                                              'longitude'])
        user_deployment.save()
        data = {'error': 'false', 'message': 'Your deployment has been created successfully'}
        # messages.add_message(request, messages.SUCCESS, 'Your deployment has been created successfully')
        return JsonResponse(data)
    else:
        # messages.add_message(request, messages.WARNING, form.errors)
        data = {'error': 'true', 'message': form.errors}
        return JsonResponse(data)
        # return redirect('crowdusers:deployment')


def persist_deployment_images(request, **kwargs):
    random_deployment_number = kwargs.get('rand_deployment_number')
    if not 'rdn_%s' % random_deployment_number in request.session:
        request.session['random_deployment_number'] = random_deployment_number
        request.session['rdn_%s' % random_deployment_number] = True
    form = DeploymentImagesForm(request.POST, request.FILES)
    if form.is_valid():
        image = form.save(commit=False)
        image.deployment_number = request.session['random_deployment_number']
        image.save()
        data = {'is_valid': True, 'name': image.file.name, 'url': image.file.url}
    else:
        data = {'is_valid': False}
    return JsonResponse(data)


def forward_report_to_response_body(request):
    dep_id = request.POST['dep_id']
    response_body = request.POST['response_bodies']
    dep = Deployment.objects.get(pk=dep_id)
    CrowdSourcingUtils.send_report_to_response_body_email(forward_report_to_response_body, settings.EMAIL_HOST_USER, response_body, dep, settings.APP_BASE_URI)
    messages.success(request, 'Report has been forwarded to %s ' % response_body)
    return redirect('crowdusers:index')

crowdusers/templates/crowdusers/fragments/base-index.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>{% block title %} Crowdsourcing for Rural Urban Areas {% endblock %}</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Bootstrap CSS CDN -->
{% if not deployment %}
<link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
{% endif %}
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
{% if deployment %}
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'crowdusers/styles/s-a/bootstrap.min.css' %}"/>
{% endif %}
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'crowdusers/styles/s-a/custom-css.css' %}"/>
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'crowdusers/styles/dropzone.css' %}"/>
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'crowdusers/styles/login-ui.css' %}"/>

<!-- SmartAdmin Styles : Caution! DO NOT change the order -->
<!-- <link rel="stylesheet" type="text/css" media="screen" th:href="@{/styles/s-a/smartadmin-production-plugins.min.css"> -->
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'crowdusers/styles/s-a/smartadmin-production.min.css' %}"/>
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'crowdusers/styles/bootstrap-tabs/b4vtabs.min.css' %}"/>
<style>
    #dep-location {
	position: relative;
   width: 100%;
   height: 300px;
   background-color: grey;
}


    #map {
	position: relative;
   width: 100%;
   height: 350px;
   background-color: grey;
}

.footer {
  position: fixed;
  left: 0;
  bottom: 0;
  width: 100%;
  background-color: #212529;
  color: white;
  text-align: center;
}
</style>
</head>
<body id="top" style="background-color: #2A2D34; color: grey;">

{% block content %} {% endblock %}

</body>
</html>

crowdusers/templates/crowdusers/fragments/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>{% block title %} Crowdsourcing for Rural Urban Areas {% endblock %}</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% load static %}
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'crowdusers/styles/s-a/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'crowdusers/styles/s-a/font-awesome.min.css' %}">
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'crowdusers/styles/dropzone.css' %}">
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'crowdusers/styles/login-ui.css' %}">

<!-- SmartAdmin Styles : Caution! DO NOT change the order -->
<!-- <link rel="stylesheet" type="text/css" media="screen" th:href="@{/styles/s-a/smartadmin-production-plugins.min.css"> -->
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'crowdusers/styles/s-a/smartadmin-production.min.css' %}">

<!-- <link rel="stylesheet" type="text/css" media="screen" th:href="@{/styles/s-a/custom-css.css}"> -->
<link href="{% static 'crowdusers/styles/layou.css' %}" rel="stylesheet" type="text/css"	media="all">
</head>
<body id="top">

{% block content %} {% endblock %}

</body>
</html>

crowdusers/templates/crowdusers/fragments/deployment-scripts.html
{% load static %}
{# JQUERY FILE UPLOAD SCRIPTS #}
  <script src="{% static 'crowdusers/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'crowdusers/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'crowdusers/jquery-file-upload/jquery.fileupload.js' %}"></script>

  {# PHOTOS PAGE SCRIPTS #}
  <script src="{% static 'crowdusers/scripts/deployment-images-upload.js' %}"></script>

<script>
    $(document).ready(function () {
       $(".form-bootstrapWizard > li").click(function(){
        if($(this).hasClass("disabled"))
            return false;
     });
    })
</script>

<script>
	var reportHasResponseBodies=false, fileArr = [], optionOtherSelectedForHowUserLearnedAboutReport=false;
		$(document)
				.ready(
						function() {

							pageSetUp();

							$('#reportdate')
									.datepicker(
											{
												dateFormat : 'dd.mm.yy',
												prevText : '<i class="fa fa-chevron-left"></i>',
												nextText : '<i class="fa fa-chevron-right"></i>',
												onSelect : function(
														selectedDate) {
													$('#reportdate').value = selectedDate;
												}
											});


							//Bootstrap Wizard Validations

							var $validator = $("#wizard-1")
									.validate(
											{

												rules : {
													nameofreport : {
														required : true
													},
													natureofreport : {
														required : true
													},
													reportdescription : {
														required : true
													},
													reporter : {
														required : true
													},
													latitude : {
														required : true
													},
													longitude : {
														required : true
													},
													reportdate : {
														required : true
													},
													reporttime : {
														required : true
													},
													tframeofreport : {
														required : true
													}
												},

												messages : {
													nameofreport   : "Please provide a very brief and simple description of report",
													natureofreport : "You need to tick the option(s) that apply to your report",
													reportdescription : "Please provide a vivid and clear description of your report as much as you can",
													reporter : "You need to tick the option that apply to your report",
													latitude : "Please specify the latitude of your report location",
													longitude : "Please specify the longitude of your report location",
													reportdate : "Please specify the date for this report",
													reporttime : "Please specify the time for this report",
													tframeofreport : "Please specify the time frame for this report"
												},

												highlight : function(element) {
													$(element)
															.closest(
																	'.form-group')
															.removeClass(
																	'has-success')
															.addClass(
																	'has-error');
												},
												unhighlight : function(element) {
													$(element)
															.closest(
																	'.form-group')
															.removeClass(
																	'has-error')
															.addClass(
																	'has-success');
												},
												errorElement : 'span',
												errorClass : 'help-block',
												errorPlacement : function(
														error, element) {
													if (element
															.parent('.input-group').length) {
														error
																.insertAfter(element
																		.parent());
													} else {
														error
																.insertAfter(element);
													}
												}
											});

							$('#bootstrap-wizard-1')
									.bootstrapWizard(
											{
												'tabClass' : 'form-wizard',
												'onNext' : function(tab,
														navigation, index) {
													var $valid = $("#wizard-1")
															.valid();
													if (!$valid) {
														$validator
																.focusInvalid();
														return false;
													} else {
														$('#bootstrap-wizard-1')
																.find(
																		'.form-wizard')
																.children('li')
																.eq(index - 1)
																.addClass(
																		'complete');
														$('#bootstrap-wizard-1')
																.find(
																		'.form-wizard')
																.children('li')
																.eq(index - 1)
																.find('.step')
																.html(
																		'<i class="fa fa-check"></i>');
													}
												}
											});

							$('#bootstrap-wizard-1 .finish').click(function(e) {
								e.preventDefault();
								createDeployment();
								});

							/*
							Create deployment validations
							*/

							//hide other source of report & response bodies on first load and page refresh
							$("#otherreporter").hide();
							$("#responsefrombodies").hide();
							$('input:radio[name="reporter"]').change(function() {
						        if ($(this).val() === 'Other') {
						            optionOtherSelectedForHowUserLearnedAboutReport = true;
						           $("#otherreporter").show();
						         } else {
						            optionOtherSelectedForHowUserLearnedAboutReport = false;
						        	$("#otherreporter").hide();
						       }
						    });

							$('input:checkbox[name="responsefrombodiesval"]').change(function() {
								 if($(this).prop("checked") === true){
									 reportHasResponseBodies=true;
									 $("#responsefrombodies").show();
								    }else{
								    	$("#responsefrombodies").hide();
								    }
						        });

							  function createDeployment(){
							    /*
							    * do extra validations before submitting post - [if user selects option "other" in 'how did you get
							    * to know of this report' user must enter a value in the 'specify how you learned about this report'
							    * textbox]
							     */
							    if(optionOtherSelectedForHowUserLearnedAboutReport===true){
							        //alert("works")
                                }
				                var natureofreport, reporter, responsebodies;
				                natureofreport = $("input.natureofreport:checkbox:checked").map(function () {
				                      return this.value;
				                   }).get().join(",");

				                	reporter = $("input:radio[name=reporter]:checked").val()==="Other" ? $("#bopc-report").val():
				                		$("input:radio[name=reporter]:checked").val();

				                	responsebodies=reportHasResponseBodies===true?$("#responsebodies").val():"";

							    var form = $('#wizard-1')[0];
								var data = new FormData();
								data.append("report_brief_description", $("#nameofreport").val());
								data.append("report_nature", natureofreport);
								data.append("report_full_description", $("#reportdescription").val());
								data.append("reporter_background",  reporter);
								data.append("latitude", $("#latitude").val());
								data.append("longitude", $("#longitude").val());
								data.append("report_date", $("#reportdate").val());
								data.append("report_time", $("#reporttime").val());
								data.append("report_time_frame", $("#tframeofreport").val());
								data.append("report_response_bodies", responsebodies);
								data.append("report_video_link", $("#videolink").val());

                                 var token = '{{ csrf_token }}';
				                    //send data via ajax
									$.ajax({
                                    headers: {"X-CSRFToken": token},
									type        : 'POST',
									enctype :'multipart/form-data',
									url         : '{% url 'crowdusers:persist_deployment' %}',
									data        : data,
								    processData: false,
								    contentType: false,
								    cache: false
								     }).done(function(data) {
								     	//console.log(data);
								     if(data.error==="true"){
							          //get the error response and display appropriate msg to user
                                         console.log(data.message);
                                         alert("Error: Please make sure you supply all required fields");
							     	   }else{
								         alert("Success: " + data.message);
							     		//$('#wizard-1')[0].reset();
							     		//window.location.href="{% url 'crowdusers:deployment' %}"
							     	  }
									}).fail(function(xhr, status, error){
										console.log("error occured " + status + " error msg " + error);
									});
								}

						})
	</script>

	<script>
		var map, infoWindow, marker;
		function initMap(latitude, longitude) {

			infoWindow = new google.maps.InfoWindow;

			// Try HTML5 geolocation.
			if (navigator.geolocation) {
				navigator.geolocation
						.getCurrentPosition(
								function(position) {
									var pos = {
										lat : position.coords.latitude,
										lng : position.coords.longitude
									};

									map = new google.maps.Map(document
											.getElementById('map'), {
										zoom : 6,
										center : pos
									});

									//zoom into user's current location
									map.setZoom(15);

									marker = new google.maps.Marker({
										position : pos,
										map : map
									});

									document.getElementById("latitude").value = position.coords.latitude;
									document.getElementById("longitude").value = position.coords.longitude;

									marker
											.addListener(
													'click',
													function() {
														document
																.getElementById("latitude").value = "";
														document
																.getElementById("longitude").value = "";
														document
																.getElementById("latitude").value = position.coords.latitude;
														document
																.getElementById("longitude").value = position.coords.longitude;
													});

									google.maps.event
											.addListener(
													map,
													'click',
													function(e) {
														document
																.getElementById("lat").value = "";
														document
																.getElementById("long").value = "";
														document
																.getElementById("lat").value = e.latLng
																.lat();
														document
																.getElementById("long").value = e.latLng
																.lng();
													});

									infoWindow.setPosition(pos);
									infoWindow
											.setContent('Your approximate current location');
									infoWindow.open(map, marker);
									map.setCenter(pos);
								}, function() {
									handleLocationError(true, infoWindow, map
											.getCenter());
								});
			} else {
				// Browser doesn't support Geolocation
				handleLocationError(false, infoWindow, map.getCenter());
			}
		}

		function handleLocationError(browserHasGeolocation, infoWindow, pos) {
			infoWindow.setPosition(pos);
			infoWindow.setContent(browserHasGeolocation ? 'Error: The Geolocation service failed.'
							: 'Error: Your browser doesn\'t support geolocation.');
			infoWindow.open(map);
		}
	</script>
	<script async defer
		src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDtZeGCdqb5KqAG5ROpf1d6oUdAVwzTpyc&callback=initMap"></script>

crowdusers/templates/crowdusers/fragments/messages.html
    {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.level_tag}} alert-dismissible text-center" role="alert">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
							{{ message.message }}
                </div>
            {% endfor %}
       {% endif %}

crowdusers/templates/crowdusers/fragments/nav-index.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand text-info" href="{% url 'crowdusers:index' %}">C.S.F.R.U.A</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav text-info">
      <a class="nav-item nav-link {% if deployment %} active {% endif %}" href="{% url 'crowdusers:deployment' %}">Discover deployments</a>
      <a class="nav-item nav-link {% if about %} active {% endif %}" href="{% url 'crowdusers:about' %}">About</a>
      {% comment %}<a class="nav-item nav-link {% if contact %} active {% endif %}" href="{% url 'crowdusers:contact' %}">Contact Us</a>{% endcomment %}
    </div>

   <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
  <ul class="navbar-nav">
      {% if not request.user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'login' %}">Login</a>
    </li>
       {% endif %}
      {% if request.user.is_authenticated %}
      <li class="nav-item">
     <a class="nav-item nav-link" href="{% url 'logout' %}"><i class="fa fa-sign-out"></i></a>
    </li>
      {% endif %}
  </ul>
</div>
  </div>
  </nav>

crowdusers/templates/crowdusers/fragments/nav.html
<div class="row" role="navigation">
<article class="col-sm-12">
<nav class="navbar navbar-default navbar-inverse fixed-top" style="padding: .5rem 1rem !important;background-color: #343a40 !important;">
  <a class="navbar-brand text-info" href="{% url 'crowdusers:index' %}" style="color: #117a8b !important;">C.S.F.R.U.A</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav text-info" style="flex-direction: row !important;font-size: 1.7rem !important;font-weight: 400 !important;
    line-height: 0.8 !important;text-align: left !important;padding-right: 8.5rem; !important;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,sans-serifApple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;">
      <a class="nav-item nav-link {% if deployment %} active {% endif %}" href="{% url 'crowdusers:deployment' %}" style="color: rgba(255,255,255,.5) !important; padding-right: .5rem !important;
padding-left: .5rem !important;">Discover deployments</a>
      <a class="nav-item nav-link {% if about %} active {% endif %}" href="{% url 'crowdusers:about' %}" style="color: rgba(255,255,255,.5) !important; padding-right: .5rem !important;
padding-left: .5rem !important;">About</a>
      {% comment %}<a class="nav-item nav-link {% if contact %} active {% endif %}" href="{% url 'crowdusers:contact' %}" style="color: rgba(255,255,255,.5) !important; padding-right: .5rem !important;
padding-left: .5rem !important;">Contact Us</a>{% endcomment %}
      {% if not request.user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'login' %}" style="color: rgba(255,255,255,.5) !important; padding-right: .5rem !important;
padding-left: .5rem !important;">Login</a>
          {% else %}
        <a class="nav-item nav-link" href="{% url 'logout' %}"><i class="fa fa-sign-out"></i></a>
      {% endif %}
    </div>

{% comment %}   <div class="collapse navbar-collapse" id="navbarCollapse">
  <ul class="navbar-nav navbar-right">
      {% if not request.user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'login' %}">Login</a>
    </li>
    {% endif  %}
      {% if request.user.is_authenticated %}
      <li class="nav-item">
     <a class="nav-item nav-link" href="{% url 'logout' %}"><i class="fa fa-sign-out"></i></a>
    </li>
      {% endif %}
  </ul>
</div>{% endcomment %}
  </div>
  </nav>

</article>
</div>