crowdsourceadmin/urls.py
from django.urls import path
from .views import *

app_name = 'crowdsourceadmin'
urlpatterns = [
    path('', index, name='index'),
    path('deployments/', deployments, name='deployments'),
    path('users/', users, name='users'),
    path('response-bodies/', response_bodies, name='response_bodies'),
    path('persist-response-body/', persist_response_body, name='persist_response_body'),
    path('users/update-status/<int:user_pk>/', update_user_status, name='update_user_status'),
]

crowdsourcing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from .views import *


#admin.site.site_header = 'Peda Reporter'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crowdusers.urls')),
    path('api/v1/', include('mobile_api.urls')),
    path('admin-site/', include('crowdsourceadmin.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/activate/<str:username>/', Account.activate_user_account, name='activate_account'),
    path('accounts/reset-password/', Account.change_password, name="reset_password"),
    path('accounts/reset-password/send-email/', Account.send_password_reset_email, name="send_password_reset_email"),
    path('accounts/signup/', Account.as_view(), name='signup'),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
]

crowdusers/urls.py
from django.urls import path
from .views import *

app_name = 'crowdusers'
urlpatterns = [
    path('', index, name="index"),
    path('about-us/', about, name="about"),
    path('contact-us/', contact, name="contact"),
    path('create-deployment/', deployment, name="deployment"),
    path('create-deployment/persist-deployment/', persist_deployment, name="persist_deployment"),
    path('deployments/<int:dep_pk>/', get_single_deployment_details, name="single_deployment_details"),
    path('deployments/single-deployment-details/<int:dep_pk>/', single_deployment_details, name="single_deployment_details_template"),
    path('forward-to-response-body/', forward_report_to_response_body, name='forward_report_to_response_body'),
    #path('deployments/location/<str:lat>/<str:lng>/', get_location_from_latlng, name="get_location_from_latlng"),
    path('create-deployment/persist-deployment-images/<int:rand_deployment_number>/', persist_deployment_images, name="persist_deployment_images"),
]

crowdsourceadmin/views.py
from django.shortcuts import render, redirect
from crowdusers.forms import *
from crowdusers.models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from datetime import datetime, timedelta


@login_required
def index(request):
    context = {
        'total_users': User.objects.count(),
        'total_deployments': Deployment.objects.count(),
        'todays_deployments': Deployment.objects.filter(created_date__gte=datetime.now() - timedelta(days=1)).count(),
    }
    return render(request, 'crowdsourceadmin/index.html', context)


@login_required
def deployments(request):
    context = {
        'deployments': Deployment.objects.all()
    }
    return render(request, 'crowdsourceadmin/deployments.html', context)


@login_required
def users(request):
    context = {
        'users': User.objects.all().order_by('-date_joined'),
    }
    return render(request, 'crowdsourceadmin/users.html', context)


@login_required
def response_bodies(request):
    context = {
        'response_bodies': CustomUser.objects.all().order_by('-date_joined'),
        'form': ResponseBodyForm()
    }
    return render(request, 'crowdsourceadmin/response-bodies.html', context)


@login_required
def persist_response_body(request):
    form = ResponseBodyForm(request.POST)
    if form.is_valid():
        # check to see if response body already exist. If it exists we want to update else we'll create a new body
        pk = request.POST.get('id')
        if pk != 'None':
            resp_body_instance = CustomUser.objects.get(pk=pk)
            form = ResponseBodyForm(request.POST, instance=resp_body_instance)
            messages.add_message(request, messages.SUCCESS,
                                 'Response body with name "%s' % resp_body_instance.display_name + '" has been updated')
            form.save()
        else:
            if CustomUser.objects.filter(display_name=form.cleaned_data['display_name']).exists():
                messages.add_message(request, messages.ERROR,
                                     'A response body with name %s ' % form.cleaned_data['display_name'] +
                                     ' already exist. Please specify a different name')
            else:
                CustomUser.objects.create(**form.cleaned_data)
                #User.objects.create(username=form.cleaned_data['display_name'], password=form.cleaned_data['password'],
                                    #email=form.cleaned_data['email'], is_active=True)
                messages.add_message(request, messages.SUCCESS,
                                 'Response body with name "%s' % form.cleaned_data['display_name'] + '" has been created')
    else:
        messages.add_message(request, messages.ERROR,
                             form.errors)
    return redirect('crowdsourceadmin:response_bodies')


@login_required
def update_user_status(request, **kwargs):
    try:
        pk = kwargs.get('user_pk')
        user = User.objects.get(pk=pk)
        user.is_active = not user.is_active
        user.save()
        messages.add_message(request, messages.SUCCESS,
                             'Active status of "%s' % user.username + '" has been updated to %s ' % user.is_active)
    except User.DoesNotExist:
        messages.add_message(request, messages.ERROR,
                             "We couldn't find an account for the user with an id of %s '" % pk + "'")
    return redirect('crowdsourceadmin:users')

crowdsourceadmin/templates/crowdsourceadmin/cron-jobs.html
{% extends 'crowdsourceadmin/fragments/base.html' %}
{% block title %} Admin | Cron Jobs {% endblock %}

{% block content %}

    <div id="wrapper">

        {% include 'crowdsourceadmin/fragments/top-bar.html' %}

        {% include 'crowdsourceadmin/fragments/left-side-bar.html' %}

       <!-- ============================================================== -->
		<!-- Start right Content here -->
		<!-- ============================================================== -->
		<div class="content-page">
			<!-- Start content -->
			<div class="content">
				<div class="container">

					<!-- Page-Title -->
					<div class="row">
                        {% include 'crowdsourceadmin/fragments/messages.html' %}
						<div class="col-sm-12">
                            <form action="{% url 'crowdsourceadmin:get_news_updates_cron' %}" method="get" id="fetch-news-form"></form>
                            <button type="button" class="btn btn-warning" id="run-cron-manually">Manually Fetch News Updates</button>
							<ol class="breadcrumb pull-right">
								<li><a href="#">GhNewsHub</a></li>
                                <li><a href="#">Admin Section</a></li>
                                <li class="active">Cron Jobs</li>
							</ol>
						</div>
					</div>

					<div class="panel">
						<div class="panel-body">
							<div class="row">
								<div class="col-sm-6">
									<div class="m-b-30"></div>
								</div>
							</div>
							<div class="col-md-12 col-sm-12 col-xs-12 table-responsive">
							<form id="frmDisableAccount">
								<table class="table table-bordered table-striped" id="datatable">
									<thead>
										<tr>
											<th>Code</th>
											<th>Start Time</th>
											<th>End Time</th>
											<th>Duration</th>
                                            <th>Success</th>
										</tr>
									</thead>
									<tbody>
                                    {% for cron in cron_jobs %}
										<tr>
                                          <td>{{ cron.code }}</td>
                                          <td>{{ cron.start_time }}</td>
                                          <td>{{ cron.end_time }}</td>
                                          <td>{{ cron.end_time|timesince:cron.start_time}}</td>
                                          <td>{{ cron.is_success }}</td>
                                        </tr>
                                    {% endfor %}
									</tbody>
								</table>
								</form>
							</div>
						</div>
					</div>

				</div>
				<!-- container -->

			</div>
			<!-- content -->
        </div>

      </div>

{% include 'crowdsourceadmin/fragments/footer.html' %}
{% include 'crowdsourceadmin/fragments/bootbox-messages.html' %}

<script>
  $(document).ready(function(){
     $('#datatable').dataTable();

$("#run-cron-manually").on('click', function (e) {
    e.preventDefault();

    bootbox.dialog({
						title: "<span style='color: #07689F;'>News Updates Cron Job</span>",
						  size: "medium",
						  message: "Do you really want to manually fetch news update from the webhose.io API?",
                           buttons: {
                            danger:{
                                label: "No",
                                className: "btn-danger"
                            },
                            success:{
                                label: "Yes",
                                className: "btn-primary",
                                    callback: function(e){
                                          e.preventDefault();
                                            $("#fetch-news-form").submit();
                               }
                         }
	                }
             });

     })
  });
</script>

{% endblock %}

crowdsourceadmin/templates/crowdsourceadmin/index.html
{% extends 'crowdsourceadmin/fragments/base.html' %}
{% block title %} Admin | User {% endblock %}

{% block content %}

    <div id="wrapper">

        {% include 'crowdsourceadmin/fragments/top-bar.html' %}

        {% include 'crowdsourceadmin/fragments/left-side-bar.html' %}

       <!-- ============================================================== -->
		<!-- Start right Content here -->
		<!-- ============================================================== -->
		<div class="content-page">
			<!-- Start content -->
			<div class="content">
				<div class="container">

					<!-- Page-Title -->
					<div class="row">
                      {% include 'crowdsourceadmin/fragments/messages.html' %}
						<div class="col-sm-12">
							<ol class="breadcrumb pull-right">
								<li><a href="#">Crowdsourcing for Rural Urban Areas</a></li>
                                <li><a href="#">Admin Section</a></li>
                                <li class="active">Dashboard</li>
							</ol>
						</div>
					</div>

					<div class="panel">
						<div class="panel-body">
							<div class="row">
								<div class="col-sm-6">
									<div class="m-b-30"></div>
								</div>
							</div>
							<div class="col-md-12 col-sm-12 col-xs-12 table-responsive">
                                  <!-- Start Widget -->
                        <div class="row">
                            <div class="col-md-6 col-sm-6 col-lg-4">
                                <div class="mini-stat clearfix bx-shadow">
                                    <span class="mini-stat-icon bg-info"><i class="fa fa-medkit"></i></span>
                                    <div class="mini-stat-info text-right text-muted">
                                        <span class="">{{ total_deployments }}</span>
                                        Total
                                    </div>
                                    <div class="tiles-progress">
                                        <div class="m-t-20">
                                            <h5 class="text-uppercase">All Deployments <span class="pull-right"></span></h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-6 col-lg-4">
                                <div class="mini-stat clearfix bx-shadow">
                                    <span class="mini-stat-icon bg-purple"><i class="fa fa-file-text"></i></span>
                                    <div class="mini-stat-info text-right text-muted">
                                        <span class="">{{ total_users }}</span>
                                        Total
                                    </div>
                                    <div class="tiles-progress">
                                        <div class="m-t-20">
                                            <h5 class="text-uppercase">Registered Users (Crowdsourcees) <span class="pull-right"></span></h5>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6 col-sm-6 col-lg-4">
                                <div class="mini-stat clearfix bx-shadow">
                                    <span class="mini-stat-icon bg-success"><i class="fa fa-th-list"></i></span>
                                    <div class="mini-stat-info text-right text-muted">
                                        <span class="">{{ todays_deployments }}</span>
                                        Total
                                    </div>
                                    <div class="tiles-progress">
                                        <div class="m-t-20">
                                            <h5 class="text-uppercase">Today's Total Deployments<span class="pull-right"></span></h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <canvas id="myChart" width="400" height="150"></canvas>
                        </div>
                        <!-- End row-->
							</div>
						</div>
					</div>

				</div>
				<!-- container -->

			</div>
			<!-- content -->
        </div>

      </div>

{% include 'crowdsourceadmin/fragments/footer.html' %}
<script>
                 var ctx = document.getElementById("myChart").getContext('2d');
                 var totalDeployments="{{ total_deployments }}";
                 var totalRegisteredUsers="{{ total_users }}";
                 var todaysTotalDeployment="{{ total_deployments }}";
                 var myChart = new Chart(ctx, {
                	  type: 'pie',
                	  data: {
                	    labels: ["Total Deployments", "Total Registered Users", "Today's Total Deployments"],
                	    datasets: [{
                	      backgroundColor: [
                	        "#2ecc71",
                	        "#3498db",
                	        "#95a5a6"
                	      ],
                	      data: [totalDeployments, totalRegisteredUsers, todaysTotalDeployment]
                	    }]
                	  }
                	});
                 </script>
{% endblock %}

crowdsourceadmin/templates/crowdsourceadmin/response-bodies.html
{% extends 'crowdsourceadmin/fragments/base.html' %}
{% block title %} Admin | Response Bodies {% endblock %}

{% block content %}

    <div id="wrapper">

        {% include 'crowdsourceadmin/fragments/top-bar.html' %}

        {% include 'crowdsourceadmin/fragments/left-side-bar.html' %}

       <!-- ============================================================== -->
		<!-- Start right Content here -->
		<!-- ============================================================== -->
		<div class="content-page">
			<!-- Start content -->
			<div class="content">
				<div class="container">

					<!-- Page-Title -->
					<div class="row">
                      {% include 'crowdsourceadmin/fragments/messages.html' %}
						<div class="col-sm-12">
                           {% comment %} <a href="#" data-toggle="modal" data-target="#myModal2" class="btn btn-primary add" ><i
								class="fa fa-plus-square" aria-hidden="true"></i> New</a>{% endcomment %}
							<ol class="breadcrumb pull-right">
								<li><a href="#">Crowdsourcing for Rural Urban Areas</a></li>
                                <li><a href="#">Admin Section</a></li>
                                <li class="active">Response Bodies</li>
							</ol>
						</div>
					</div>

					<div class="panel">
						<div class="panel-body">
							<div class="row">
								<div class="col-sm-6">
									<div class="m-b-30"></div>
								</div>
							</div>
							<div class="col-md-12 col-sm-12 col-xs-12 table-responsive">
							<form id="frmDisableAccount">
								<table class="table table-bordered table-striped" id="datatable">
									<thead>
										<tr>
											<th>Body Name</th>
											<th>Email</th>
											<th>Active</th>
											<th>Staff</th>
											<th>Superuser</th>
											<th>Date Joined</th>
                                            <th>Last Login</th>
											{% comment %}<th>Actions</th>{% endcomment %}
										</tr>
									</thead>
									<tbody>
                                    {% for user in response_bodies %}
										<tr>
                                          <input type="hidden" value="{{ user.id }}" />
                                          <td>{{ user.display_name }}</td>
                                          <td>{{ user.email }}</td>
                                          <td>{{ user.is_active }}</td>
                                          <td>{{ user.is_staff }}</td>
                                          <td>{{ user.is_superuser }}</td>
                                            {% load humanize %}
                                          <td>{{ user.date_joined|naturalday }}</td>
                                          <td>{{ user.last_login }}</td>
{#                                          <td>#}
{#                                              {% if not user.is_superuser %}#}
{#                                              <a href="#" class="on-default update-user" data-balloon="Edit user details" data-balloon-pos="up"><i class="fa fa-edit"></i></a>#}
{#											&nbsp;&nbsp</a>#}
{#                                              {% endif %}#}
{#                                          </td>#}
                                        </tr>
                                    {% endfor %}
									</tbody>
								</table>
								</form>
							</div>
						</div>
					</div>

				</div>
				<!-- container -->

			</div>
			<!-- content -->
        </div>

      </div>

  <div class="modal fade" id="myModal2" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title title" style="color: #07689F;">Add Response Body</h4>
      </div>
      <br/>
    <div class="container-fluid">
          <form action="{% url 'crowdsourceadmin:persist_response_body' %}" method="post" enctype="multipart/form-data">
         {% include 'crowdsourceadmin/fragments/form-fields.html' %}
		    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> Close</button>
        <button type="submit" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i> Save</button>
            </div>
            </form>
    </div>
            </div>
      </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->

{% include 'crowdsourceadmin/fragments/footer.html' %}

<script>
  $(document).ready(function(){
     $('#datatable').dataTable();

 $("#datatable").on('click', '.update-user', function(){
	var currentRow=$(this).closest('tr');
	var id=currentRow.find("input:eq(0)").val();
	var username=currentRow.find("td:eq(0)").text();
	var active_status=currentRow.find("td:eq(4)").text();

	//negate active status
     function negate_active_status(is_user_active){
         if(is_user_active==="True"){
             return "False";
         }else{
             return "True";
         }
     }


	bootbox.dialog({
						title: "<span style='color: #07689F;'>Update " + username + "'s active status</span>",
						  size: "medium",
						  message: "Do you really want to change this response body's active status from " + active_status + " to " + negate_active_status(active_status) + "?",
                           buttons: {
                            danger:{
                                label: "No",
                                className: "btn-danger"
                            },
                            success:{
                                label: "Yes",
                                className: "btn-primary",
                                    callback: function(e){
                                          e.preventDefault();
                                            var token = '{{ csrf_token }}';
					         	             $.ajax({
                                                    headers: {"X-CSRFToken": token},
                                                      type: 'POST',
                                                      url: "{% url 'crowdsourceadmin:update_user_status'  user_pk=1 %}".replace(/1/, id.toString()),
                                                      success: function (response) {
                                                        //refresh page if request is successful
                                                        window.location.href="{% url 'crowdsourceadmin:users' %}";
                                                          },
                                                      error: function (response) {
                                                          //alert(response)
                                                           }
                                                      })
                               }
                         }
	                }
             });


   });

  });
</script>
{% endblock %}

crowdsourceadmin/templates/crowdsourceadmin/users.html
{% extends 'crowdsourceadmin/fragments/base.html' %}
{% block title %} Admin | User {% endblock %}

{% block content %}

    <div id="wrapper">

        {% include 'crowdsourceadmin/fragments/top-bar.html' %}

        {% include 'crowdsourceadmin/fragments/left-side-bar.html' %}

       <!-- ============================================================== -->
		<!-- Start right Content here -->
		<!-- ============================================================== -->
		<div class="content-page">
			<!-- Start content -->
			<div class="content">
				<div class="container">

					<!-- Page-Title -->
					<div class="row">
                      {% include 'crowdsourceadmin/fragments/messages.html' %}
						<div class="col-sm-12">
                            <a href="#" data-toggle="modal" data-target="#myModal2" class="btn btn-primary add" ><i
								class="fa fa-plus-square" aria-hidden="true"></i> New</a>
							<ol class="breadcrumb pull-right">
								<li><a href="#">Crowdsourcing for Rural Urban Areas</a></li>
                                <li><a href="#">Admin Section</a></li>
                                <li class="active">Users</li>
							</ol>
						</div>
					</div>

					<div class="panel">
						<div class="panel-body">
							<div class="row">
								<div class="col-sm-6">
									<div class="m-b-30"></div>
								</div>
							</div>
							<div class="col-md-12 col-sm-12 col-xs-12 table-responsive">
							<form id="frmDisableAccount">
								<table class="table table-bordered table-striped" id="datatable">
									<thead>
										<tr>
											<th>Full Name</th>
											<th>Username</th>
											<th>Email</th>
											<th>Active</th>
											<th>Staff</th>
											<th>Superuser</th>
											<th>Date Joined</th>
                                            <th>Last Login</th>
											<th>Actions</th>
										</tr>
									</thead>
									<tbody>
                                    {% for user in users %}
										<tr>
                                          <input type="hidden" value="{{ user.id }}" />
                                          <td>{{ user.first_name }} {{ user.last_name }}</td>
                                          <td>{{ user.username }}</td>
                                          <td>{{ user.email }}</td>
                                          <td>{{ user.is_active }}</td>
                                          <td>{{ user.is_staff }}</td>
                                          <td>{{ user.is_superuser }}</td>
                                            {% load humanize %}
                                          <td>{{ user.date_joined|naturalday }}</td>
                                          <td>{{ user.last_login }}</td>
                                          <td>
                                              {% if not user.is_superuser %}
                                              <a href="#" class="on-default update-user" data-balloon="Edit user details" data-balloon-pos="up"><i class="fa fa-edit"></i></a>
											&nbsp;&nbsp</a>
                                              {% endif %}
                                          </td>
                                        </tr>
                                    {% endfor %}
									</tbody>
								</table>
								</form>
							</div>
						</div>
					</div>

				</div>
				<!-- container -->

			</div>
			<!-- content -->
        </div>

      </div>

  <div class="modal fade" id="myModal2" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title title" style="color: #07689F;">Add User</h4>
      </div>
      <br/>
    <div class="container-fluid">
          <form action="" method="post" enctype="multipart/form-data">
         {% include 'crowdsourceadmin/fragments/form-fields.html' %}
		    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> Close</button>
        <button type="submit" class="btn btn-primary"><i class="fa fa-save" aria-hidden="true"></i> Save</button>
            </div>
            </form>
    </div>
            </div>
      </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->

{% include 'crowdsourceadmin/fragments/footer.html' %}

<script>
  $(document).ready(function(){
     $('#datatable').dataTable();

 $("#datatable").on('click', '.update-user', function(){
	var currentRow=$(this).closest('tr');
	var id=currentRow.find("input:eq(0)").val();
	var username=currentRow.find("td:eq(1)").text();
	var active_status=currentRow.find("td:eq(4)").text();

	//negate active status
     function negate_active_status(is_user_active){
         if(is_user_active==="True"){
             return "False";
         }else{
             return "True";
         }
     }


	bootbox.dialog({
						title: "<span style='color: #07689F;'>Update " + username + "'s active status</span>",
						  size: "medium",
						  message: "Do you really want to change this user's active status from " + active_status + " to " + negate_active_status(active_status) + "?",
                           buttons: {
                            danger:{
                                label: "No",
                                className: "btn-danger"
                            },
                            success:{
                                label: "Yes",
                                className: "btn-primary",
                                    callback: function(e){
                                          e.preventDefault();
                                            var token = '{{ csrf_token }}';
					         	             $.ajax({
                                                    headers: {"X-CSRFToken": token},
                                                      type: 'POST',
                                                      url: "{% url 'crowdsourceadmin:update_user_status'  user_pk=1 %}".replace(/1/, id.toString()),
                                                      success: function (response) {
                                                        //refresh page if request is successful
                                                        window.location.href="{% url 'crowdsourceadmin:users' %}";
                                                          },
                                                      error: function (response) {
                                                          //alert(response)
                                                           }
                                                      })
                               }
                         }
	                }
             });


   });

  });
</script>
{% endblock %}