crowdsourceadmin/urls.py
from django.urls import path
from .views import *

app_name = 'crowdsourceadmin'
urlpatterns = [
    path('', index, name='index'),
    path('deployments/', deployments, name='deployments'),
    path('users/', users, name='users'),
    path('response-bodies/', response_bodies, name='response_bodies'),
    path('persist-response-body/', persist_response_body, name='persist_response_body'),
    path('users/update-status/<int:user_pk>/', update_user_status, name='update_user_status'),
]

crowdsourcing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve
from .views import *


#admin.site.site_header = 'Peda Reporter'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crowdusers.urls')),
    path('api/v1/', include('mobile_api.urls')),
    path('admin-site/', include('crowdsourceadmin.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/activate/<str:username>/', Account.activate_user_account, name='activate_account'),
    path('accounts/reset-password/', Account.change_password, name="reset_password"),
    path('accounts/reset-password/send-email/', Account.send_password_reset_email, name="send_password_reset_email"),
    path('accounts/signup/', Account.as_view(), name='signup'),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
]

crowdusers/urls.py
from django.urls import path
from .views import *

app_name = 'crowdusers'
urlpatterns = [
    path('', index, name="index"),
    path('about-us/', about, name="about"),
    path('contact-us/', contact, name="contact"),
    path('create-deployment/', deployment, name="deployment"),
    path('create-deployment/persist-deployment/', persist_deployment, name="persist_deployment"),
    path('deployments/<int:dep_pk>/', get_single_deployment_details, name="single_deployment_details"),
    path('deployments/single-deployment-details/<int:dep_pk>/', single_deployment_details, name="single_deployment_details_template"),
    path('forward-to-response-body/', forward_report_to_response_body, name='forward_report_to_response_body'),
    #path('deployments/location/<str:lat>/<str:lng>/', get_location_from_latlng, name="get_location_from_latlng"),
    path('create-deployment/persist-deployment-images/<int:rand_deployment_number>/', persist_deployment_images, name="persist_deployment_images"),
]

crowdsourceadmin/views.py
from django.shortcuts import render, redirect
from crowdusers.forms import *
from crowdusers.models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from datetime import datetime, timedelta


@login_required
def index(request):
    context = {
        'total_users': User.objects.count(),
        'total_deployments': Deployment.objects.count(),
        'todays_deployments': Deployment.objects.filter(created_date__gte=datetime.now() - timedelta(days=1)).count(),
    }
    return render(request, 'crowdsourceadmin/index.html', context)


@login_required
def deployments(request):
    context = {
        'deployments': Deployment.objects.all()
    }
    return render(request, 'crowdsourceadmin/deployments.html', context)


@login_required
def users(request):
    context = {
        'users': User.objects.all().order_by('-date_joined'),
    }
    return render(request, 'crowdsourceadmin/users.html', context)


@login_required
def response_bodies(request):
    context = {
        'response_bodies': CustomUser.objects.all().order_by('-date_joined'),
        'form': ResponseBodyForm()
    }
    return render(request, 'crowdsourceadmin/response-bodies.html', context)


@login_required
def persist_response_body(request):
    form = ResponseBodyForm(request.POST)
    if form.is_valid():
        # check to see if response body already exist. If it exists we want to update else we'll create a new body
        pk = request.POST.get('id')
        if pk != 'None':
            resp_body_instance = CustomUser.objects.get(pk=pk)
            form = ResponseBodyForm(request.POST, instance=resp_body_instance)
            messages.add_message(request, messages.SUCCESS,
                                 'Response body with name "%s' % resp_body_instance.display_name + '" has been updated')
            form.save()
        else:
            if CustomUser.objects.filter(display_name=form.cleaned_data['display_name']).exists():
                messages.add_message(request, messages.ERROR,
                                     'A response body with name %s ' % form.cleaned_data['display_name'] +
                                     ' already exist. Please specify a different name')
            else:
                CustomUser.objects.create(**form.cleaned_data)
                #User.objects.create(username=form.cleaned_data['display_name'], password=form.cleaned_data['password'],
                                    #email=form.cleaned_data['email'], is_active=True)
                messages.add_message(request, messages.SUCCESS,
                                 'Response body with name "%s' % form.cleaned_data['display_name'] + '" has been created')
    else:
        messages.add_message(request, messages.ERROR,
                             form.errors)
    return redirect('crowdsourceadmin:response_bodies')


@login_required
def update_user_status(request, **kwargs):
    try:
        pk = kwargs.get('user_pk')
        user = User.objects.get(pk=pk)
        user.is_active = not user.is_active
        user.save()
        messages.add_message(request, messages.SUCCESS,
                             'Active status of "%s' % user.username + '" has been updated to %s ' % user.is_active)
    except User.DoesNotExist:
        messages.add_message(request, messages.ERROR,
                             "We couldn't find an account for the user with an id of %s '" % pk + "'")
    return redirect('crowdsourceadmin:users')

crowdsourceadmin/templates/crowdsourceadmin/fragments/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>{% block title %} {% endblock %}</title>
<meta http-equiv="Content-Type" content="text/html;" charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="{% static '/admin/css2/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static '/admin/css2/font-awesome.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static '/admin/ionicon/css/ionicons.min.css' %}" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css"/>
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css"/>
<link rel="stylesheet" href="https://cdn.datatables.net/select/1.2.5/css/select.dataTables.min.css"/>
<link href="{% static '/admin/css2/animate.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static '/admin/css2/waves-effect.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static '/admin/css2/balloon.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static '/admin/css2/helper.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static '/admin/css2/admin-style.css' %}" rel="stylesheet" type="text/css"/>
<link href='https://cdn.jsdelivr.net/npm/froala-editor@3.1.1/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

<link href="{% static '/admin/css2/footable.metro.css' %}" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
<link href="{% static '/admin/css2/tabs.css' %}" rel="stylesheet" type="text/css"/>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.js"></script>
<script src="{% static '/admin/js2/modernizr.min.js' %}"></script>
<!--[if lt IE 9]>
<script src="{% static '/admin/js2/html5shiv.min.js' %}"></script>
<script src="{% static '/admin/js2/respond.min.js' %}"></script>
<![endif]-->
</head>
<body class="fixed-left">
{% block content %} {% endblock %}
</body>
</html>

crowdsourceadmin/templates/crowdsourceadmin/fragments/bootbox-messages.html
<script>

    function bootBoxMessages(title, message, redirect_url){
        bootbox.dialog({
						title: "<span style='color: #07689F;'>" + title + "</span>",
						  size: "medium",
						  message: message,
                          buttons: {
								success:{
					         		label: "Close",
					         		className: "btn-info",
                                    callback: function(e){
					         		    e.preventDefault();
					         		    window.location.href=redirect_url;
                                    }
					         	}
						}
             });
    }

</script>

crowdsourceadmin/templates/crowdsourceadmin/fragments/footer.html
<div class="navbar-fixed-bottom">
<footer class="footer text-right"> &copy 2020 Crowdsourcing for Rural Urban Areas </footer>

		<script>
            var resizefunc = [];
        </script>

    {% load static %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static '/admin/js2/bootbox.min.js' %}"></script>
<script src="{% static '/admin/js2/jquery-blockui/jquery.blockUI.js' %}"></script>
<script src="{% static '/admin/js2/bootstrap.min.js' %}"></script>
<script src="{% static '/admin/js2/page_popups.js' %}"></script>
<script src="{% static '/admin/js2/waves.js' %}"></script>
<script src="{% static '/admin/js2/wow.min.js' %}"></script>
<script src="{% static '/admin/js2/jquery.nicescroll.js' %}"></script>
<script src="{% static '/admin/js2/jquery-detectmobile/detect.js' %}"></script>
<script src="{% static '/admin/js2/fastclick/fastclick.js' %}"></script>
<script src="{% static '/admin/js2/jquery.li-scroller.1.0.js' %}"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@3.1.1/js/froala_editor.pkgd.min.js'></script>
<script>
  new FroalaEditor('textarea#froala-editor')
</script>

<!-- CUSTOM JS --->
<script src="{% static '/admin/js2/jquery.app.js' %}"></script>
<script src="{% static '/admin/js2/jquery.validate.js' %}"></script>
</div>

crowdsourceadmin/templates/crowdsourceadmin/fragments/form-fields.html
    <div class="row" id="form-fields">
             {% csrf_token %}
    <input type="hidden" value="{{ form.instance.id }}" name="id"/>
            {% for field in form %}
           <div class="form-group col-4">
                <label class="col-8">{{field.label}}</label>
                {{ field }}
            </div>
             {% endfor %}
    </div>

crowdsourceadmin/templates/crowdsourceadmin/fragments/left-side-bar.html
		<!-- ========== Left Sidebar Start ========== -->
		<div class="left side-menu">
                     <div class="sidebar-inner slimscrollleft">
                           <div class="user-details">
                        <div class="pull-left">
                            <img src="{{ MEDIA_URL }}/media/images/avatar-1.jpg" alt="user-img" class="thumb-sm img-circle" />
                        </div>
                         <div class="user-info">
                            <div class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <span>{{request.user.username}}</span> <span class="caret"></span></a>
                                <br/>
                                <ul class="dropdown-menu">
                                   <!--   <li><a href="javascript:void(0)"><i class="md md-vpn-key"></i> Reset Pasword</a></li>
                                         <li><a href="lock-screen.php"><i class="md md-lock"></i> Lock screen</a></li> -->
                                        <li><a href="{% url 'logout' %}"><i class="zmdi zmdi-power zmdi-hc-lg"></i> Logout</a></li>
                                </ul>
                            </div>

                            <!-- <p class="text-muted m-0"><span sec:authentication="authorities">Role </span></p> -->
                        </div>
                    </div>
                           <!--- Divider -->
                           <div id="sidebar-menu">
                                  <ul>
                                         <li><a href="{% url 'crowdsourceadmin:index' %}" class="waves-effect"><i
                                                       class="zmdi zmdi-view-dashboard" aria-hidden="true"></i> <span>Dashboard
                                                </span></a></li>
                                            <li class="has_sub"><a href="#" class="waves-effect"><i
                                                       class="zmdi zmdi-collection-item"></i><span>Deployment </span><span
                                                       class="pull-right"><i class="zmdi zmdi-caret-down zmdi-hc-lg"></i></span></a>
                                                <ul class="list-unstyled">
                                                <li><a href="{% url 'crowdsourceadmin:deployments' %}" class="waves-effect">Created Deployments</a></li>
                                                <li><a href="{% url 'crowdsourceadmin:response_bodies' %}" class="waves-effect">Response Bodies</a></li>
                                                {% load admin_extras %}
                                                {% if request.user|has_group:'Basic Admin' %}
                                                <li><a href="" class="waves-effect">Categories</a></li>
                                                <li><a href="" class="waves-effect">Messages</a></li>
                                                <li><a href="" class="waves-effect">Video Section Details</a></li>
                                                {% endif %}
                                                </ul>
                                                </li>
                                              {% if request.user.is_superuser %}
                                              <li class="has_sub"><a href="#" class="waves-effect"><i
                                                       class="zmdi zmdi-accounts-list"></i><span>User Management </span><span
                                                       class="pull-right"><i class="zmdi zmdi-caret-down zmdi-hc-lg"></i></span></a>
                                                <ul class="list-unstyled">
                                                <li><a href="{% url 'crowdsourceadmin:users' %}" class="waves-effect">All Users </a></li>
                                                </ul>
                                               </li>
                                              {% endif %}
                                      {% if request.user|has_group:'Basic Admin' %}
                                      <li class="has_sub"><a href="#" class="waves-effect"><i
                                                       class="zmdi zmdi-time"></i><span>Cron </span><span
                                                       class="pull-right"><i class="zmdi zmdi-caret-down zmdi-hc-lg"></i></span></a>
                                                <ul class="list-unstyled">
                                                <li><a href="" class="waves-effect">Cron Jobs </a></li>
                                                </ul>
                                       </li>
                                      {% endif %}
                                  </ul>
                                  <div class="clearfix"></div>
                           </div>
                           <div class="clearfix"></div>
                     </div>
              </div>
		<!-- Left Sidebar End -->

crowdsourceadmin/templates/crowdsourceadmin/fragments/messages.html
         {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.level_tag}} alert-dismissible text-center" role="alert">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
							{{ message.message }}
                </div>
            {% endfor %}
       {% endif %}

crowdsourceadmin/templates/crowdsourceadmin/fragments/top-bar.html
<!-- Top Bar Start -->
		<div class="topbar">
			<!-- LOGO -->
			<div class="topbar-left">
				<div class="text-center">
					<a href="" class="logo">
						<span> C.F.R.U.A </span></a>
				</div>
			</div>
			<!-- Button mobile view to collapse sidebar menu -->
			<div class="navbar navbar-default" role="navigation">
				<div class="container">
					<div class="">
						<div class="pull-left">
							<button class="button-menu-mobile open-left">
								<i class="fa fa-bars"></i>
							</button>
							<span class="clearfix"></span>
						</div>
						<!-- <form class="navbar-form pull-left" role="search">
                                <div class="form-group">
                                    <input type="text" class="form-control search-bar" placeholder="Type here for search...">
                                </div>
                                <button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
                            </form> -->

				<ul class="nav navbar-nav navbar-right pull-right">
                                         <li class="dropdown hidden-xs">
                                    <a href="#" data-target="#" class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="true">
                                        <i class="md md-notification"></i> <span class="badge badge-xs badge-danger"></span>
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-lg">
                                        <li class="text-center notifi-title">Notification</li>
                                        <li class="list-group">
                                           <!-- last list item -->
                                            <a href="javascript:void(0);" class="list-group-item">
                                              <small>See all notifications</small>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="hidden-xs">
                  <a href="#" id="btn-fullscreen" class="waves-effect waves-light"><i class="zmdi zmdi-fullscreen zmdi-hc-lg"></i></a>
                                 </li>
           <li class="dropdown"><a href="#" class="dropdown-toggle profile" data-toggle="dropdown" aria-expanded="true"></a>
              <a href="#" class="dropdown-toggle profile" data-toggle="dropdown" aria-expanded="true">
              <img src="{{ MEDIA_URL }}/media/images/avatar-1.jpg" alt="user-img" class="thumb-sm img-circle" />
              </a>
             <ul class="dropdown-menu">
      <!-- <li><a href="javascript:void(0)"><i class="md md-vpn-key"></i> Reset Pasword</a></li>
       <li><a href="#"><i class="md md-lock"></i> Lock screen</a></li> -->
      <li><a href="{% url 'logout' %}"><i class="zmdi zmdi-power zmdi-hc-lg"></i> Logout</a></li>
       </ul></li>
         </ul>
					</div>
					<!--/.nav-collapse -->
				</div>
			</div>
		</div>
		<!-- Top Bar End -->